# Generated by Django 5.0 on 2023-12-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeDriver', models.CharField(default='', max_length=255)),
                ('NamaDriver', models.CharField(default='', max_length=255)),
                ('Kantor', models.CharField(default='', max_length=255)),
                ('NamaUnit', models.CharField(default='', max_length=255)),
                ('Status', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        
    ]
