# Generated by Django 5.0 on 2023-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_permintaan_unit_alter_driver_kodedriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permintaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodePermintaan', models.CharField(default='', max_length=255)),
                ('NomerSuratJalan', models.CharField(default='', max_length=255)),
                ('NamaPermintaan', models.CharField(default='', max_length=255)),
                ('TitikAntar', models.CharField(default='', max_length=255)),
                ('TitikJemput', models.CharField(default='', max_length=255)),
                ('KodeDriver', models.CharField(default='', max_length=255)),
                ('NamaDriver', models.CharField(default='', max_length=255)),
                ('KodeUnit', models.CharField(default='', max_length=255)),
                ('NamaUnit', models.CharField(default='', max_length=255)),
                ('PlatNomor', models.CharField(default='', max_length=255)),
                ('KodeUser', models.CharField(default='', max_length=255)),
                ('NamaUser', models.CharField(default='', max_length=255)),
                ('StatusPermintaan', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Permintaan',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeUnit', models.CharField(default='', max_length=255)),
                ('NamaUnit', models.CharField(default='', max_length=255)),
                ('PlatNomor', models.CharField(default='', max_length=255)),
                ('NomerRangka', models.CharField(default='', max_length=255)),
                ('NomerMesin', models.CharField(default='', max_length=255)),
                ('Kantor', models.CharField(default='', max_length=255)),
                ('Status', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
    ]
