# Generated by Django 5.0 on 2023-12-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_permintaan_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permintaan',
            name='KodeDriver',
        ),
        migrations.RemoveField(
            model_name='permintaan',
            name='KodeUnit',
        ),
        migrations.RemoveField(
            model_name='permintaan',
            name='KodeUser',
        ),
        migrations.RemoveField(
            model_name='permintaan',
            name='NamaUser',
        ),
        migrations.RemoveField(
            model_name='permintaan',
            name='PlatNomor',
        ),
    ]
