# Generated by Django 5.0 on 2023-12-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_permintaan_kodedriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permintaan',
            name='StatusPermintaan',
        ),
    ]
